[book]
title = "The MiniJuvix Book"
authors =  [ "Jonathan Prieto-Cubides" , "Jan Mas Rovira" , "Paul Cadman" ]
language = "en"
multilingual = false
src = "docs/md/"

[build]
build-dir = "_docs"
create-missing = true

[output.html]
mathjax-support = true
