name:            minijuvix
version:         0.0.0.0
license:         GPL-3.0-only
license-file:    LICENSE
copyright:       (c) 2021-2022 Heliax AG.
maintainer:      The PLT Team at Heliax AG <hello@heliax.dev>
author:          [ Jonathan Prieto-Cubides , Jan Mas Rovira , Paul Cadman ]
tested-with:     ghc == 9.2.2
homepage:        https://github.com/heliaxdev/MiniJuvix
bug-reports:     https://github.com/heliaxdev/MiniJuvix/issues
description:     A tiny dependent typed programming language for experimentation.
category:        Compilers/Interpreters
github:          heliaxdev/MiniJuvix

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- aeson == 2.0.*
- algebraic-graphs == 0.6.*
- base == 4.16.*
- blaze-html == 0.9.*
- blaze-markup == 0.8.*
- bytestring == 0.11.*
- containers == 0.6.*
- directory == 1.3.*
- edit-distance == 0.2.*
- extra == 1.7.*
- filepath == 1.4.*
- hashable == 1.4.*
- megaparsec == 9.2.*
- microlens-platform == 0.4.*
- parser-combinators == 1.3.*
- polysemy == 1.7.*
- polysemy-plugin == 0.4.*
- prettyprinter == 1.7.*
- prettyprinter-ansi-terminal == 1.1.*
- process == 1.6.*
- semirings == 0.6.*
- singletons == 3.0.*
- singletons-th == 3.1.*
- Stream == 0.4.*
- template-haskell == 2.18.*
- text == 1.2.*
- th-utilities == 0.2.*
- unordered-containers == 0.2.*

# the tasty dependencies are here to avoid having to recompile minijuvix
# when running the tests. Is there a better solution?
- tasty
- tasty-hunit

ghc-options:
- -fhide-source-paths
- -O2 -flate-specialise -fspecialise-aggressively
- -Wall -Wcompat -Widentities -Wincomplete-uni-patterns
- -Wderiving-defaults -Wredundant-constraints
- -Wincomplete-patterns
- -Wincomplete-record-updates -fwrite-ide-info -hiedir=.hie
- -Wmissing-deriving-strategies

default-extensions:
- DataKinds
- DerivingStrategies
- GADTs
- LambdaCase
- NoImplicitPrelude
- OverloadedStrings
- QuasiQuotes
- RecordWildCards
- TemplateHaskell
- TypeFamilyDependencies
- UnicodeSyntax

# verbatim:
#   default-language: GHC2021

library:
  source-dirs: src
  verbatim:
    default-language: GHC2021

executables:
  minijuvix:
    main: Main.hs
    source-dirs: app
    dependencies:
    - minijuvix
    - optparse-applicative == 0.17.*
    - pretty-show == 1.10.*
    verbatim:
      default-language: GHC2021

tests:
  minijuvix-test:
    main:                Main.hs
    source-dirs:         test
    dependencies:
    - minijuvix
    verbatim:
      default-language: GHC2021
