name:            MiniJuvix
version:         0.0.0.0
license:         GPL-3.0-only
license-file:    LICENSE
copyright:       2021 Heliax AG
maintainer:      Jonathan Prieto-Cubides <jonathan@heliax.dev>, Jan Mas Rovira <jan@heliax.dev>
author:          [Jonathan Prieto-Cubides]
tested-with:     ghc == 9.0.1
homepage:        https://github.com/heliaxdev/MiniJuvix
bug-reports:     https://github.com/heliaxdev/MiniJuvix/issues
description:     A tiny dependent typed programming language for experimentation.
category:        Compilers/Interpreters
github:          heliaxdev/MiniJuvix

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- aeson
- base
- bytestring
- containers
- filepath
- megaparsec
- polysemy
- polysemy-plugin
- prettyprinter
- prettyprinter-ansi-terminal
- process
- relude
- semirings
- unordered-containers
- word8

ghc-options:
- -O2 -flate-specialise -fspecialise-aggressively
- -Wincomplete-patterns
- -fplugin=Polysemy.Plugin
- -Wall -Wcompat -Widentities -Wincomplete-uni-patterns
- -Wincomplete-record-updates -fwrite-ide-info -hiedir=.hie
- -Wderiving-defaults -Wredundant-constraints
- -fhide-source-paths -Wpartial-fields
- -Wmissing-deriving-strategies

default-extensions:
- ApplicativeDo
- BlockArguments
- DataKinds
- DeriveDataTypeable
- DeriveLift
- DerivingStrategies
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- GADTs
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PolyKinds
- QuasiQuotes
- RankNTypes
- RecordWildCards
- Safe
- ScopedTypeVariables
- StandaloneDeriving
- StandaloneKindSignatures
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- UndecidableInstances
- UnicodeSyntax
- ViewPatterns

library:
  source-dirs: src

executables:
  MiniJuvix:
    main: Main.hs
    source-dirs: src/app
    dependencies:
    - MiniJuvix

tests:
  curry-test:
    main:                Spec.hs
    source-dirs:         src/test
    dependencies:
    - curry
    - tasty
    - tasty-hunit
